# Generated by Django 4.2.7 on 2023-11-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profileimg_post',
            field=models.ImageField(default='default.png', upload_to='profile_images_for_post'),
        ),
    ]
